# Generated by Django 2.2.6 on 2019-10-19 11:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='account_name',
            field=models.CharField(max_length=50, null=True, verbose_name='account name'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='account_number',
            field=models.CharField(max_length=11, null=True, verbose_name='account number'),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='customuser',
            name='bank_name',
            field=models.CharField(max_length=255, null=True, verbose_name='bank name'),
        ),
    ]
