# Generated by Django 2.2.6 on 2019-11-12 12:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0002_auto_20191106_0204'),
        ('accounts', '0004_transaction'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='transaction',
            name='content_type',
        ),
        migrations.RemoveField(
            model_name='transaction',
            name='object_id',
        ),
        migrations.AddField(
            model_name='transaction',
            name='farm',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfund.Farm'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='transaction',
            name='transaction_type',
            field=models.CharField(choices=[('purchase', 'Purchase'), ('dividends', 'Dividends')], max_length=50),
        ),
    ]
