# Generated by Django 2.2.6 on 2019-11-12 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_auto_20191112_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='transaction',
            name='description',
            field=models.TextField(),
            preserve_default=False,
        ),
    ]
