# Generated by Django 2.2.6 on 2019-10-19 18:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='PManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('P', 'Project Manager')], max_length=50)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'project manager',
                'verbose_name_plural': 'project managers',
            },
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField()),
                ('duration', models.PositiveSmallIntegerField()),
                ('location', models.CharField(max_length=150)),
                ('insurance_statement', models.TextField()),
                ('insured', models.BooleanField(default=True)),
                ('units', models.PositiveIntegerField()),
                ('unit_in_stock', models.PositiveIntegerField()),
                ('price_per_unit', models.PositiveIntegerField()),
                ('roi', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='images/farm/%Y/')),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfund.Category')),
                ('project_manger', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfund.PManager', verbose_name='project manager')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('project_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='crowdfund.Project')),
                ('stage', models.CharField(max_length=50, verbose_name='farm stage')),
                ('harvest_date', models.DateField()),
            ],
            options={
                'verbose_name': 'farm',
                'verbose_name_plural': 'farms',
            },
            bases=('crowdfund.project',),
        ),
    ]
