# Generated by Django 2.2.6 on 2019-11-05 23:52

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import djmoney.models.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField(null=True)),
                ('slug', models.SlugField(max_length=255)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'category',
                'verbose_name_plural': 'categories',
            },
        ),
        migrations.CreateModel(
            name='Farm',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField()),
                ('status', models.CharField(choices=[('open', 'Open'), ('close', 'Closed'), ('sold_out', 'Sold out')], default='close', max_length=50)),
                ('duration', models.PositiveSmallIntegerField()),
                ('location', models.CharField(max_length=150)),
                ('insurance_statement', models.TextField()),
                ('insured', models.BooleanField(default=True)),
                ('units', models.PositiveIntegerField()),
                ('unit_in_stock', models.PositiveIntegerField()),
                ('price_per_unit_currency', djmoney.models.fields.CurrencyField(choices=[('NGN', 'NGN ₦')], default='NGN', editable=False, max_length=3)),
                ('price_per_unit', djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=14)),
                ('roi', models.PositiveSmallIntegerField()),
                ('image', models.ImageField(upload_to='images/farm/%Y/')),
                ('stage', models.CharField(max_length=50, verbose_name='farm stage')),
                ('harvest_date', models.DateField()),
                ('start_date', models.DateField()),
                ('end_date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfund.Category')),
            ],
            options={
                'verbose_name': 'project',
                'verbose_name_plural': 'projects',
            },
        ),
        migrations.CreateModel(
            name='Update',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('activity', models.CharField(max_length=255)),
                ('slug', models.SlugField(max_length=255)),
                ('description', models.TextField()),
                ('report', models.TextField()),
                ('date', models.DateField()),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('farm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfund.Farm')),
            ],
            options={
                'verbose_name': 'Farm update',
                'verbose_name_plural': 'Farm updates',
            },
        ),
        migrations.CreateModel(
            name='FarmManager',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('P', 'Project Manager'), ('F', 'Farm Manager')], max_length=50)),
                ('manager', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'farm manager',
                'verbose_name_plural': 'farm managers',
            },
        ),
        migrations.AddField(
            model_name='farm',
            name='manger',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfund.FarmManager', verbose_name='farm manager'),
        ),
    ]
