# Generated by Django 2.2.6 on 2019-11-06 01:04

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='farm',
            options={'verbose_name': 'farm', 'verbose_name_plural': 'farms'},
        ),
        migrations.CreateModel(
            name='UpdateImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='images/farm/%Y')),
                ('position', models.PositiveSmallIntegerField()),
                ('update', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='crowdfund.Update')),
            ],
            options={
                'verbose_name': 'Update Image',
                'verbose_name_plural': 'Update Images',
            },
        ),
    ]
