# Generated by Django 2.2.6 on 2019-10-20 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0002_category_description'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pmanager',
            options={'verbose_name': 'project and farm manager', 'verbose_name_plural': 'project and farm managers'},
        ),
        migrations.AlterField(
            model_name='pmanager',
            name='role',
            field=models.CharField(choices=[('P', 'Project Manager'), ('F', 'Farm Manager')], max_length=50),
        ),
    ]
