# Generated by Django 2.2.6 on 2019-11-12 17:27

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0003_investment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='investment',
            name='units',
            field=models.PositiveIntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
        ),
    ]
