# Generated by Django 2.2.6 on 2019-10-20 23:58

from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0003_auto_20191020_1721'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='price_per_unit_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'NGN ₦')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AlterField(
            model_name='project',
            name='price_per_unit',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=14),
        ),
    ]
