# Generated by Django 2.2.6 on 2019-11-17 17:28

from decimal import Decimal
from django.db import migrations
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0004_auto_20191112_1827'),
    ]

    operations = [
        migrations.AddField(
            model_name='farm',
            name='raised',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='NGN', max_digits=14),
        ),
        migrations.AddField(
            model_name='farm',
            name='raised_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'NGN ₦')], default='NGN', editable=False, max_length=3),
        ),
        migrations.AddField(
            model_name='farm',
            name='target',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default=Decimal('0'), default_currency='NGN', max_digits=14),
        ),
        migrations.AddField(
            model_name='farm',
            name='target_currency',
            field=djmoney.models.fields.CurrencyField(choices=[('NGN', 'NGN ₦')], default='NGN', editable=False, max_length=3),
        ),
    ]
