# Generated by Django 2.2.6 on 2019-10-22 18:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0005_update'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='status',
            field=models.CharField(choices=[('open', 'Open'), ('close', 'Closed'), ('sold_out', 'Sold out')], default='close', max_length=50),
        ),
    ]
