# Generated by Django 2.2.6 on 2019-11-17 17:59

from django.db import migrations, models
import djmoney.models.fields


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0006_auto_20191117_1832'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='transaction_id',
            field=models.CharField(max_length=100),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='farm',
            name='target',
            field=djmoney.models.fields.MoneyField(decimal_places=2, default_currency='NGN', max_digits=14),
        ),
    ]
