# Generated by Django 2.2.6 on 2019-12-20 11:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0007_auto_20191117_1859'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='farm',
            name='manger',
        ),
    ]
