# Generated by Django 2.2.6 on 2019-12-20 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0009_farmmanager_farm'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmmanager',
            name='role',
            field=models.CharField(choices=[('Project Manager', 'Project Manager'), ('Farm Manager', 'Farm Manager')], max_length=50),
        ),
    ]
