# Generated by Django 2.2.6 on 2020-05-13 17:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crowdfund', '0010_auto_20191220_1410'),
    ]

    operations = [
        migrations.AddField(
            model_name='investment',
            name='reference',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
